In [2]:
# Standard scientific Python imports
import matplotlib.pyplot as plt
import numpy as np
import time
import datetime as dt
import os

# Import datasets, classifiers and performance metrics
from sklearn import svm, metrics

In [3]:
# Import whole N-MNIST Dataset
def load_NMNIST(path):
    """
    """
    xs_train = []
    ys_train = []
    xs_test = []
    ys_test = []

    for class_index in range(0, 10):
        for (root, dirs, dat_files) in os.walk('{0}/n_Train_3/{1}'.format(path, str(class_index))):
            for file in dat_files:
                single_X = np.fromfile('{0}/n_Train_3/{1}/{2}'.format(path, str(class_index), file), dtype=np.int32)
                xs_train.append(single_X)
                ys_train.append(class_index)

        for (root, dirs, dat_files) in os.walk('{0}/n_Test_3/{1}'.format(path, str(class_index))):
            for file in dat_files:
                xs_test.append(np.fromfile('{0}/n_Test_3/{1}/{2}'.format(path, str(class_index), file), dtype=np.int32))
                ys_test.append(class_index)

    Xtr = np.array(xs_train)
    Ytr = np.array(ys_train)
    Xte = np.array(xs_test)
    Yte = np.array(ys_test)

    return Xtr, Ytr, Xte, Yte

In [4]:
dataset_class_path = '/Users/brunocalogero/Desktop/LowPowerActionRecognition/CNN/NMNIST/datasets'
X_train, Y_train, X_test, Y_test = load_NMNIST(dataset_class_path)

In [5]:
# As a sanity check, we print out the size of the training and test data.
print('Training data shape: ', X_train.shape)
print('Training labels shape: ', Y_train.shape)
print('Test data shape: ', X_test.shape)
print('Test labels shape: ', Y_test.shape)

('Training data shape: ', (60000, 2312))
('Training labels shape: ', (60000,))
('Test data shape: ', (10000, 2312))
('Test labels shape: ', (10000,))


In [10]:
num_training = 60000
num_dev = 60000


# We will also make a development set, which is a small subset of
# the training set.
mask = np.random.choice(num_training, num_dev, replace=False)
X_dev = X_train[mask]
Y_dev = Y_train[mask]

In [14]:
# As a sanity check, we print out the size of the training and test data.
print('Training data shape: ', X_dev.shape)
print('Training labels shape: ', Y_dev.shape)

('Training data shape: ', (60000, 2312))
('Training labels shape: ', (60000,))


In [ ]:
classifier = svm.SVC(C=5,kernel='rbf',gamma=0.01,cache_size=8000,probability=False)

start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))

classifier.fit(X_dev, Y_dev)

end_time = dt.datetime.now() 
print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))

Start learning at 2018-12-02 17:15:35.962169


In [ ]:
# Now predict the value of the test
expected = Y_test
predicted = classifier.predict(X_test)


print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
      
cm = metrics.confusion_matrix(expected, predicted)
print("Confusion matrix:\n%s" % cm)

# plot_confusion_matrix(cm)

print("Accuracy={}".format(metrics.accuracy_score(expected, predicted)))

In [12]:
classifier = svm.SVC(C=1,kernel='rbf',gamma=0.0005,cache_size=8000,probability=False)

start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))

classifier.fit(X_dev, Y_dev)

end_time = dt.datetime.now() 
print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))

Start learning at 2018-12-04 03:08:02.840172
Stop learning 2018-12-04 03:50:42.299998
Elapsed learning 0:42:39.459826


In [13]:
# Now predict the value of the test
expected = Y_test
predicted = classifier.predict(X_test)


print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
      
cm = metrics.confusion_matrix(expected, predicted)
print("Confusion matrix:\n%s" % cm)

# plot_confusion_matrix(cm)

print("Accuracy={}".format(metrics.accuracy_score(expected, predicted)))

Classification report for classifier SVC(C=1, cache_size=8000, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.0005, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.96      0.98      0.97       980
          1       0.97      0.99      0.98      1135
          2       0.95      0.97      0.96      1032
          3       0.97      0.96      0.97      1010
          4       0.96      0.97      0.96       982
          5       0.96      0.96      0.96       892
          6       0.97      0.97      0.97       958
          7       0.97      0.95      0.96      1028
          8       0.96      0.94      0.95       974
          9       0.96      0.94      0.95      1009

avg / total       0.96      0.96      0.96     10000


Confusion matrix:
[[ 962    0    3    2    0    4    2    3    3    1]
 [   0 1126    2    2    0  

In [7]:
classifier = svm.SVC(C=1,kernel='rbf',gamma=0.0005,cache_size=8000,probability=False)

start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))

classifier.fit(X_train, Y_train)

end_time = dt.datetime.now() 
print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))

Start learning at 2018-12-06 12:43:46.470860
Stop learning 2018-12-06 13:21:58.853775
Elapsed learning 0:38:12.382915


In [8]:
# Now predict the value of the test
expected = Y_test
predicted = classifier.predict(X_test)


print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
      
cm = metrics.confusion_matrix(expected, predicted)
print("Confusion matrix:\n%s" % cm)

# plot_confusion_matrix(cm)

print("Accuracy={}".format(metrics.accuracy_score(expected, predicted)))

Classification report for classifier SVC(C=1, cache_size=8000, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.0005, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.96      0.98      0.97       980
          1       0.97      0.99      0.98      1135
          2       0.95      0.97      0.96      1032
          3       0.97      0.96      0.97      1010
          4       0.96      0.97      0.96       982
          5       0.96      0.96      0.96       892
          6       0.97      0.97      0.97       958
          7       0.97      0.95      0.96      1028
          8       0.96      0.94      0.95       974
          9       0.96      0.94      0.95      1009

avg / total       0.96      0.96      0.96     10000


Confusion matrix:
[[ 962    0    3    2    0    4    2    3    3    1]
 [   0 1126    2    2    0  

In [9]:
classifier = svm.SVC(C=5,kernel='rbf',gamma=0.0005,cache_size=8000,probability=False)

start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))

classifier.fit(X_train, Y_train)

end_time = dt.datetime.now() 
print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))

Start learning at 2018-12-06 13:32:28.124273
Stop learning 2018-12-06 14:08:04.604238
Elapsed learning 0:35:36.479965


In [10]:
# Now predict the value of the test
expected = Y_test
predicted = classifier.predict(X_test)


print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
      
cm = metrics.confusion_matrix(expected, predicted)
print("Confusion matrix:\n%s" % cm)

# plot_confusion_matrix(cm)

print("Accuracy={}".format(metrics.accuracy_score(expected, predicted)))

Classification report for classifier SVC(C=5, cache_size=8000, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.0005, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.97      0.99      0.98       980
          1       0.98      0.99      0.99      1135
          2       0.96      0.97      0.97      1032
          3       0.96      0.97      0.97      1010
          4       0.97      0.98      0.97       982
          5       0.97      0.96      0.96       892
          6       0.98      0.97      0.97       958
          7       0.98      0.96      0.97      1028
          8       0.96      0.95      0.96       974
          9       0.97      0.95      0.96      1009

avg / total       0.97      0.97      0.97     10000


Confusion matrix:
[[ 966    0    1    2    0    2    2    3    3    1]
 [   0 1126    3    2    0  

In [11]:
classifier = svm.SVC(C=5,kernel='rbf',gamma=0.0004,cache_size=8000,probability=False)

start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))

classifier.fit(X_train, Y_train)

end_time = dt.datetime.now() 
print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))


Start learning at 2018-12-06 16:51:29.218941
Stop learning 2018-12-06 17:21:17.373048
Elapsed learning 0:29:48.154107


In [12]:
# Now predict the value of the test
expected = Y_test
predicted = classifier.predict(X_test)


print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
      
cm = metrics.confusion_matrix(expected, predicted)
print("Confusion matrix:\n%s" % cm)

# plot_confusion_matrix(cm)

print("Accuracy={}".format(metrics.accuracy_score(expected, predicted)))

Classification report for classifier SVC(C=5, cache_size=8000, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.0004, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.97      0.99      0.98       980
          1       0.97      0.99      0.98      1135
          2       0.96      0.97      0.96      1032
          3       0.96      0.97      0.97      1010
          4       0.97      0.98      0.97       982
          5       0.97      0.96      0.96       892
          6       0.98      0.97      0.97       958
          7       0.97      0.95      0.96      1028
          8       0.96      0.95      0.96       974
          9       0.97      0.95      0.96      1009

avg / total       0.97      0.97      0.97     10000


Confusion matrix:
[[ 966    0    1    2    0    2    2    3    3    1]
 [   0 1126    3    2    0  

In [13]:
classifier = svm.SVC(C=1,kernel='rbf',gamma=0.0004,cache_size=8000,probability=False)

start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))

classifier.fit(X_train, Y_train)

end_time = dt.datetime.now() 
print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))

Start learning at 2018-12-06 21:12:10.634575
Stop learning 2018-12-06 23:11:34.575331
Elapsed learning 1:59:23.940756


In [14]:
# Now predict the value of the test
expected = Y_test
predicted = classifier.predict(X_test)


print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
      
cm = metrics.confusion_matrix(expected, predicted)
print("Confusion matrix:\n%s" % cm)

# plot_confusion_matrix(cm)

print("Accuracy={}".format(metrics.accuracy_score(expected, predicted)))

Classification report for classifier SVC(C=1, cache_size=8000, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.0004, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.96      0.98      0.97       980
          1       0.97      0.99      0.98      1135
          2       0.96      0.96      0.96      1032
          3       0.97      0.96      0.96      1010
          4       0.96      0.97      0.96       982
          5       0.96      0.96      0.96       892
          6       0.97      0.97      0.97       958
          7       0.96      0.95      0.95      1028
          8       0.95      0.94      0.95       974
          9       0.96      0.94      0.95      1009

avg / total       0.96      0.96      0.96     10000


Confusion matrix:
[[ 962    0    3    2    0    4    2    3    3    1]
 [   0 1126    2    1    0  