In [1]:
# Standard scientific Python imports
import matplotlib.pyplot as plt
import numpy as np
import time
import datetime as dt
import os

# Import datasets, classifiers and performance metrics
from sklearn import svm, metrics

In [11]:
# Import whole N-MNIST Dataset
def load_NMNIST(path):
    """
    """
    xs_train = []
    ys_train = []
    xs_test = []
    ys_test = []

    for class_index in range(0, 10):
        for (root, dirs, dat_files) in os.walk('{0}/n_Train_2/{1}'.format(path, str(class_index))):
            for file in dat_files:
                single_X = np.fromfile('{0}/n_Train_2/{1}/{2}'.format(path, str(class_index), file), dtype=np.int32)
                xs_train.append(single_X)
                ys_train.append(class_index)

        for (root, dirs, dat_files) in os.walk('{0}/n_Test_2/{1}'.format(path, str(class_index))):
            for file in dat_files:
                xs_test.append(np.fromfile('{0}/n_Test_2/{1}/{2}'.format(path, str(class_index), file), dtype=np.int32))
                ys_test.append(class_index)

    Xtr = np.array(xs_train)
    Ytr = np.array(ys_train)
    Xte = np.array(xs_test)
    Yte = np.array(ys_test)

    return Xtr, Ytr, Xte, Yte

In [12]:
dataset_class_path = '/Users/brunocalogero/Desktop/LowPowerActionRecognition/CNN/NMNIST/datasets'
X_train, Y_train, X_test, Y_test = load_NMNIST(dataset_class_path)

In [13]:
# As a sanity check, we print out the size of the training and test data.
print('Training data shape: ', X_train.shape)
print('Training labels shape: ', Y_train.shape)
print('Test data shape: ', X_test.shape)
print('Test labels shape: ', Y_test.shape)

('Training data shape: ', (60000, 2312))
('Training labels shape: ', (60000,))
('Test data shape: ', (10000, 2312))
('Test labels shape: ', (10000,))


In [11]:
classifier = svm.SVC(C=5,kernel='rbf',gamma=0.01,cache_size=8000,probability=False)

start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))

classifier.fit(X_train, Y_train)

end_time = dt.datetime.now() 
print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))

Start learning at 2018-11-30 20:42:43.573398
Stop learning 2018-12-01 20:57:56.467691
Elapsed learning 1 day, 0:15:12.894293


In [12]:
# Now predict the value of the test
expected = Y_test
predicted = classifier.predict(X_test)


print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
      
cm = metrics.confusion_matrix(expected, predicted)
print("Confusion matrix:\n%s" % cm)

# plot_confusion_matrix(cm)

print("Accuracy={}".format(metrics.accuracy_score(expected, predicted)))

Classification report for classifier SVC(C=5, cache_size=8000, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       980
           1       0.99      0.76      0.86      1135
           2       0.00      0.00      0.00      1032
           3       0.87      0.04      0.07      1010
           4       1.00      0.03      0.05       982
           5       1.00      0.00      0.01       892
           6       0.95      0.02      0.04       958
           7       0.11      0.99      0.20      1028
           8       0.00      0.00      0.00       974
           9       0.87      0.05      0.09      1009

   micro avg       0.20      0.20      0.20     10000
   macro avg       0.58      0.19      0.13     10000
weighted avg       0.58      0.20   

/usr/local/lib/python2.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [14]:
classifier = svm.SVC(C=5,kernel='rbf',gamma=0.0005,cache_size=8000,probability=False)

start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))

classifier.fit(X_train, Y_train)

end_time = dt.datetime.now() 
print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))

Start learning at 2018-12-05 22:03:37.807504
Stop learning 2018-12-06 01:28:24.590395
Elapsed learning 3:24:46.782891


In [15]:
# Now predict the value of the test
expected = Y_test
predicted = classifier.predict(X_test)


print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
      
cm = metrics.confusion_matrix(expected, predicted)
print("Confusion matrix:\n%s" % cm)

# plot_confusion_matrix(cm)

print("Accuracy={}".format(metrics.accuracy_score(expected, predicted)))

Classification report for classifier SVC(C=5, cache_size=8000, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.0005, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.97      0.99      0.98       980
          1       0.97      0.99      0.98      1135
          2       0.97      0.97      0.97      1032
          3       0.96      0.97      0.96      1010
          4       0.97      0.98      0.97       982
          5       0.97      0.97      0.97       892
          6       0.98      0.97      0.98       958
          7       0.97      0.96      0.97      1028
          8       0.97      0.95      0.96       974
          9       0.96      0.94      0.95      1009

avg / total       0.97      0.97      0.97     10000


Confusion matrix:
[[ 967    1    1    1    0    3    3    3    0    1]
 [   0 1125    4    2    0  

In [16]:
classifier = svm.SVC(C=1,kernel='rbf',gamma=0.0005,cache_size=8000,probability=False)

start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))

classifier.fit(X_train, Y_train)

end_time = dt.datetime.now() 
print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))



Start learning at 2018-12-06 01:38:18.915357
Stop learning 2018-12-06 02:17:24.732880
Elapsed learning 0:39:05.817523


In [17]:
# Now predict the value of the test
expected = Y_test
predicted = classifier.predict(X_test)


print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
      
cm = metrics.confusion_matrix(expected, predicted)
print("Confusion matrix:\n%s" % cm)

# plot_confusion_matrix(cm)

print("Accuracy={}".format(metrics.accuracy_score(expected, predicted)))

Classification report for classifier SVC(C=1, cache_size=8000, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.0005, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.97      0.98      0.98       980
          1       0.97      0.99      0.98      1135
          2       0.95      0.96      0.96      1032
          3       0.97      0.96      0.96      1010
          4       0.96      0.97      0.96       982
          5       0.96      0.97      0.96       892
          6       0.98      0.97      0.97       958
          7       0.97      0.95      0.96      1028
          8       0.96      0.95      0.96       974
          9       0.96      0.93      0.95      1009

avg / total       0.96      0.96      0.96     10000


Confusion matrix:
[[ 965    1    2    0    0    3    5    3    0    1]
 [   0 1127    4    2    0  

In [18]:
classifier = svm.SVC(C=5,kernel='rbf',gamma=0.0004,cache_size=8000,probability=False)

start_time = dt.datetime.now()
print('Start learning at {}'.format(str(start_time)))

classifier.fit(X_train, Y_train)

end_time = dt.datetime.now() 
print('Stop learning {}'.format(str(end_time)))
elapsed_time= end_time - start_time
print('Elapsed learning {}'.format(str(elapsed_time)))


Start learning at 2018-12-06 14:28:39.611644
Stop learning 2018-12-06 14:56:43.962824
Elapsed learning 0:28:04.351180


In [19]:
# Now predict the value of the test
expected = Y_test
predicted = classifier.predict(X_test)


print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
      
cm = metrics.confusion_matrix(expected, predicted)
print("Confusion matrix:\n%s" % cm)

# plot_confusion_matrix(cm)

print("Accuracy={}".format(metrics.accuracy_score(expected, predicted)))

Classification report for classifier SVC(C=5, cache_size=8000, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.0004, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       0.97      0.99      0.98       980
          1       0.97      0.99      0.98      1135
          2       0.97      0.97      0.97      1032
          3       0.96      0.97      0.96      1010
          4       0.96      0.98      0.97       982
          5       0.97      0.97      0.97       892
          6       0.98      0.97      0.97       958
          7       0.98      0.96      0.97      1028
          8       0.97      0.96      0.96       974
          9       0.97      0.94      0.95      1009

avg / total       0.97      0.97      0.97     10000


Confusion matrix:
[[ 968    1    1    1    0    3    3    2    0    1]
 [   0 1126    4    2    0  